package com.hjk.hjkbookstore_backend.controller;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;
import com.hjk.hjkbookstore_backend.Autogenerated.QueryRequest;
import com.hjk.hjkbookstore_backend.Autogenerated.QueryResponse;
import com.hjk.hjkbookstore_backend.entity.Book;
import com.hjk.hjkbookstore_backend.service.BookService;
import com.hjk.hjkbookstore_backend.service.SolrService;
import org.apache.solr.client.solrj.SolrServerException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.ws.server.endpoint.annotation.Endpoint;
import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.RequestPayload;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@RestController
public class TextSearchController {
    @Autowired
    private SolrService solrService;
    @Autowired
    private BookService bookService;


    @CrossOrigin
    @RequestMapping("/query")
    public List<Book> query(@RequestParam String needle) throws SolrServerException, IOException {
//        solrService.addAll();//因为之前书籍的ID和description没有被加入solr，这行代码用于将已经存在于数据库的书籍的ID和description加入solr
        List<Book> books=new ArrayList<>();
        List<Integer> ids=solrService.query(needle);
        for(Integer id:ids)
            books.add(bookService.findBookById(id));
        return books;
    }
}
