services:
  nginx: 
    container_name: nginx
    image: nginx
    ports:
      - "80:80" 
    hostname: mysql-master
    volumes:
      - C:/Users/hjk02/nginx/nginx-1.20.2/html:/usr/share/nginx/html
      - C:/Users/hjk02/nginx/nginx-1.20.2/conf/nginx.conf:/etc/nginx/nginx.conf
      - C:/Users/hjk02/nginx/nginx-1.20.2/logs:/var/log/nginx nginx
    depends_on:
      - bookstore-1
      - bookstore-2
  
  redis:
    image: redis
    container_name: redis
    volumes:
      - C:/Users/hjk02/Redis/data:/data
      - C:/Users/hjk02/Redis/redis.windows.conf:/etc/redis/redi 
      - s.conf -d redis redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
  
  bookstore-1:
    image: springboot/bookstore
    container_name: bookstore-1
    ports:
      - "8080:8080"
    depends_on:
      - redis
    
  bookstore-2:
    image: springboot/bookstore
    container_name: bookstore-2
    ports:
      - "8088:8080"
    depends_on:
      - redis