server:
  port:
    9090
spring:
  application:
    name: Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
