version: '2' 
services:
  mysql-master: 
    build:
      context: ./                      # 声明构建的文件夹
      dockerfile: master/Dockerfile    # 声明 Docker 文件目录
    environment: # 环境变量, 支持数组或列表方式
      - "MYSQL_ROOT_PASSWORD=020101hjk"
      - "MYSQL_DATABASE=HjkMySQLBookStore" # 初始创建的数据库
    links:
      - mysql-slave01
      - mysql-slave02
    ports:
      - "33065:3306" 
    restart: always
    hostname: mysql-master

  mysql-slave01:
    build:
      context: ./
      dockerfile: slave01/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=020101hjk"
      - "MYSQL_DATABASE=HjkMySQLBookStore"
    ports:
      - "33066:3306"
    restart: always
    hostname: mysql-slave01

  mysql-slave02:
    build:
      context: ./
      dockerfile: slave02/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=020101hjk"
      - "MYSQL_DATABASE=HjkMySQLBookStore"
    ports:
      - "33067:3306"
    restart: always
    hostname: mysql-slave02